Add routes for the user to fetch and modify their configurations
openflighthpc/flight-desktop-restapi pull request #50
Opened 2021-07-12 13:29 UTC by WilliamMcCumstie

Fairly straight forward addition of two new routes:

* `GET /configs/user` - Get the current state of the user's config,
* `PATCH /configs/user` - Update the user's config

Currently `flight desktop` does not support a method for getting the user's configuration. So instead the `set` method needs to be re-purposed as a `fetch`.

---

The `desktop` input to `POST /desktops` is now optional. The default desktop will be used when omitted.

2021-08-05 17:49 UTC, benarmston requested changes
A couple of things to look at here @WilliamMcCumstie

2021-08-05 17:49 UTC, benarmston commented on app.rb
> +    DesktopConfig.update(user: current_user).to_json
We could hide that from `app.rb` by adding a `DesktopConfig.fetch` method.  Not that I feel strongly on this for a single line called from a single location.

2021-08-05 17:49 UTC, benarmston commented on app/models.rb
> +    cmd = SystemCommand.start_session(user: user)
Should this method not be performing the same check if the session fails due to verification handling that `Desktop.start` performs?

2021-08-05 17:49 UTC, benarmston commented on app/system_command.rb
> +    params = [desktop].reject(&:nil?)
`.reject(&:nil?)` can be written as `.compact`.

2021-08-09 13:39 UTC, WilliamMcCumstie commented on app.rb
> +    DesktopConfig.update(user: current_user).to_json
0523d377751850a6c3969870b25fa7f90ca46f20

2021-08-09 13:50 UTC, WilliamMcCumstie commented on app/models.rb
> +    cmd = SystemCommand.start_session(user: user)
Reworked into `Desktop.default.start_session!`

a0eefdb5581458b41508d47c4929639523fef769

2021-08-09 13:50 UTC, WilliamMcCumstie commented on app/system_command.rb
> +    params = [desktop].reject(&:nil?)
TIL, however now obsolete

2021-08-16 10:30 UTC, benarmston reviewed
Launching the default desktop looks much better.  I have a question about the API format for the config.

2021-08-16 10:30 UTC, benarmston commented on app.rb
> +    DesktopConfig.fetch(user: current_user).to_json
Should this not be in JSONAPI format too?

2021-08-16 11:11 UTC, WilliamMcCumstie commented on app.rb
> +    DesktopConfig.fetch(user: current_user).to_json
`flight-desktop-restapi` doesn't use `JSON:API`? It's response type is `application/json` with not particular formatting guide:

```
GET /configs/user
Authorization: Bearer <token>
Accepts: application/json

HTTP/2 200 OK
{
  "id": "user",
  "desktop": <desktop-type>,
  "geometry": <geometry>,
  "geometries": [
    <geometry>,
    ...
  ]
}
```

2021-08-16 17:50 UTC, benarmston commented on app.rb
> +    DesktopConfig.fetch(user: current_user).to_json
I thought it was for its other routes.  My bad.

2021-08-16 17:50 UTC, merged